kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: redis-app
spec:
  podSelector:
    matchLabels:
      app: redis-server
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: planespotter
